import { ArrowRight, Feather, ShieldCheck, Zap } from "lucide-react";
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const features = [
  {
    icon: <Zap className="h-6 w-6" />,
    title: "Real-Time AQI",
    description: "Instantly access live air quality data for your location, including detailed pollutant breakdowns.",
  },
  {
    icon: <ShieldCheck className="h-6 w-6" />,
    title: "AI-Powered Insights",
    description: "Receive personalized health advice and hazard alerts generated by our intelligent system.",
  },
  {
    icon: <Feather className="h-6 w-6" />,
    title: "Lightweight & Fast",
    description: "Designed for performance, ensuring a smooth and responsive experience even on slower networks.",
  },
];

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]">
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-4xl text-center space-y-6">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                Clean Air, Clearer Health
              </div>
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl font-headline">
                Breathe Intelligently
              </h1>
              <p className="text-lg text-muted-foreground md:text-xl">
                Saaf Hawa delivers real-time air quality monitoring and AI-driven health recommendations to help you navigate your environment safely.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/signup" className={cn(buttonVariants({ size: "lg" }))}>
                  Get Started for Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
                <Link href="/about" className={cn(buttonVariants({ variant: "outline", size: "lg" }))}>
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-muted/50">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-3 lg:gap-16">
              {features.map((feature) => (
                <div key={feature.title} className="flex flex-col items-start text-left p-6 border border-transparent hover:border-border rounded-lg transition-all">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary mb-4">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-2 font-headline">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Value Prop Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-4 max-w-3xl mx-auto">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                From Data to Daily Decisions
              </h2>
              <p className="text-muted-foreground md:text-xl/relaxed">
                We transform complex air quality metrics into simple, actionable insights. Whether you're planning your commute or protecting your family, Saaf Hawa provides the clarity you need to act confidently.
              </p>
            </div>
          </div>
        </section>
        
        {/* CTA Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-primary/10">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight font-headline">
                Take Control of Your Environment
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                Join our community and start making healthier choices today. It’s free to sign up.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
               <Button asChild size="lg">
                <Link href="/signup">Join Now</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
