import { ArrowRight, Feather, ShieldCheck, Zap, BarChart, Users, Goal, TrendingUp } from "lucide-react";
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

const features = [
  {
    icon: <BarChart className="h-6 w-6" />,
    title: "Real-Time AQI",
    description: "Access live air quality data for your location, with detailed breakdowns of pollutants like PM2.5, NO₂, and O₃.",
  },
  {
    icon: <ShieldCheck className="h-6 w-6" />,
    title: "AI-Powered Insights",
    description: "Receive personalized health advice and hazard alerts generated by our intelligent system to keep you safe.",
  },
  {
    icon: <TrendingUp className="h-6 w-6" />,
    title: "Health Journal",
    description: "Track symptoms and correlate them with air quality to understand its impact on your well-being.",
  },
  {
    icon: <Goal className="h-6 w-6" />,
    title: "Eco-Challenges",
    description: "Join community challenges, earn points for sustainable actions, and climb the leaderboard.",
  },
  {
    icon: <Users className="h-6 w-6" />,
    title: "Crowdsourced Eco-Map",
    description: "View and report environmental issues in your community, powered by real-time user submissions.",
  },
  {
    icon: <Feather className="h-6 w-6" />,
    title: "Lightweight & Fast",
    description: "Designed for performance, ensuring a smooth experience even on slower networks in Pakistan.",
  },
];

const testimonials = [
    {
        name: "Aisha K.",
        role: "Asthma Patient, Lahore",
        avatar: "https://picsum.photos/seed/aisha/40/40",
        fallback: "AK",
        text: "Saaf Hawa has been a lifesaver. The alerts help me know when to stay indoors. I feel more in control of my health."
    },
    {
        name: "Bilal M.",
        role: "Parent, Karachi",
        avatar: "https://picsum.photos/seed/bilal/40/40",
        fallback: "BM",
        text: "I use the app every day to decide if it's safe for my kids to play outside. The hazard zone feature is incredibly useful."
    },
    {
        name: "Fatima Z.",
        role: "Student, Islamabad",
        avatar: "https://picsum.photos/seed/fatima/40/40",
        fallback: "FZ",
        text: "The eco-challenges are fun and motivating! It feels great to be part of a community that's making a positive impact."
    }
]


export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]">
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-4xl text-center space-y-6">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl font-headline">
                Breathe Intelligently, Live Healthier
              </h1>
              <p className="text-lg text-muted-foreground md:text-xl max-w-2xl mx-auto">
                Saaf Hawa provides real-time air quality data, AI-driven health alerts, and community tools to help you navigate pollution in Pakistan.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/signup" className={cn(buttonVariants({ size: "lg" }))}>
                  Get Started for Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
                <Link href="#features" className={cn(buttonVariants({ variant: "outline", size: "lg" }))}>
                  Explore Features
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-muted/50">
            <div className="container px-4 md:px-6">
                 <div className="text-center max-w-3xl mx-auto mb-16">
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">From Data to Daily Action in 3 Steps</h2>
                    <p className="mt-4 text-lg text-muted-foreground">We make complex environmental data simple and actionable.</p>
                </div>
                <div className="grid gap-10 sm:grid-cols-3 text-center">
                    <div className="space-y-4">
                        <div className="inline-block rounded-full bg-primary/10 text-primary p-4">
                            <BarChart className="h-8 w-8" />
                        </div>
                        <h3 className="text-2xl font-bold font-headline">1. Get Live Data</h3>
                        <p className="text-muted-foreground">Instantly see the current Air Quality Index (AQI) for your location.</p>
                    </div>
                    <div className="space-y-4">
                        <div className="inline-block rounded-full bg-primary/10 text-primary p-4">
                            <ShieldCheck className="h-8 w-8" />
                        </div>
                        <h3 className="text-2xl font-bold font-headline">2. Receive Insights</h3>
                        <p className="text-muted-foreground">Our AI provides personalized health tips and alerts you to nearby pollution hotspots.</p>
                    </div>
                     <div className="space-y-4">
                        <div className="inline-block rounded-full bg-primary/10 text-primary p-4">
                            <Goal className="h-8 w-8" />
                        </div>
                        <h3 className="text-2xl font-bold font-headline">3. Take Action</h3>
                        <p className="text-muted-foreground">Join eco-challenges and use our tools to reduce your footprint and improve community health.</p>
                    </div>
                </div>
            </div>
        </section>

        {/* Features Section */}
        <section id="features" className="w-full py-20 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="text-center max-w-3xl mx-auto mb-16">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm mb-2">Our Features</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">A Suite of Tools for a Healthier Life</h2>
                <p className="mt-4 text-lg text-muted-foreground">Everything you need to understand and navigate your environment.</p>
            </div>
            <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <div key={feature.title} className="flex flex-col text-left p-6 border-b-2 border-transparent hover:border-primary transition-all rounded-lg hover:bg-muted/50">
                  <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary mb-4">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-2 font-headline">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-muted/50">
          <div className="container px-4 md:px-6">
             <div className="text-center max-w-3xl mx-auto mb-16">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">Loved by our Community</h2>
                <p className="mt-4 text-lg text-muted-foreground">See how Saaf Hawa is making a difference in people's lives across Pakistan.</p>
            </div>
             <div className="grid gap-8 sm:grid-cols-1 lg:grid-cols-3">
                {testimonials.map((testimonial) => (
                    <Card key={testimonial.name} className="bg-card">
                        <CardContent className="p-6">
                            <p className="mb-6 italic">"{testimonial.text}"</p>
                             <div className="flex items-center gap-4">
                                <Avatar>
                                    <AvatarImage src={testimonial.avatar} alt={testimonial.name} />
                                    <AvatarFallback>{testimonial.fallback}</AvatarFallback>
                                </Avatar>
                                <div>
                                    <p className="font-semibold">{testimonial.name}</p>
                                    <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                ))}
             </div>
          </div>
        </section>

        {/* Our Mission Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container grid items-center justify-center gap-8 px-4 text-center md:px-6">
            <div className="space-y-4 max-w-3xl mx-auto">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                Our Mission: Clean Air for All
              </h2>
              <p className="text-muted-foreground md:text-xl/relaxed">
                We believe that access to clear, real-time environmental information is a right, not a privilege. Saaf Hawa was built to empower the people of Pakistan with the tools they need to combat the effects of air pollution and build a healthier future for generations to come.
              </p>
            </div>
             <Button asChild size="lg" variant="outline">
                <Link href="/about">Learn More About Our Story</Link>
             </Button>
          </div>
        </section>
        
        {/* CTA Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-primary/10 dark:bg-muted/20">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight font-headline">
                Take Control of Your Environment
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                Join our community and start making healthier choices today. It’s free to sign up and takes less than a minute.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
               <Button asChild size="lg">
                <Link href="/signup">Join Saaf Hawa Now</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
