import { ArrowRight, Feather, ShieldCheck, Zap } from 'lucide-react';
import Link from 'next/link';
import { Button, buttonVariants } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import Marquee from '@/components/ui/marquee';

const features = [
  {
    icon: <Zap className="h-6 w-6" />,
    title: 'Real-Time AQI',
    description:
      'Instantly access live air quality data for your location, including detailed pollutant breakdowns.',
  },
  {
    icon: <ShieldCheck className="h-6 w-6" />,
    title: 'AI-Powered Insights',
    description:
      'Receive personalized health advice and hazard alerts generated by our intelligent system.',
  },
  {
    icon: <Feather className="h-6 w-6" />,
    title: 'Lightweight & Fast',
    description:
      'Designed for performance, ensuring a smooth and responsive experience even on slower networks.',
  },
];

const testimonials = [
  {
    name: 'Aisha K.',
    role: 'Asthma Patient, Lahore',
    avatar: 'https://picsum.photos/seed/aisha/40/40',
    fallback: 'AK',
    text: 'Saaf Hawa has been a lifesaver. The alerts help me know when to stay indoors. I feel more in control of my health.',
  },
  {
    name: 'Bilal M.',
    role: 'Parent, Karachi',
    avatar: 'https://picsum.photos/seed/bilal/40/40',
    fallback: 'BM',
    text: "I use the app every day to decide if it's safe for my kids to play outside. The hazard zone feature is incredibly useful.",
  },
  {
    name: 'Fatima Z.',
    role: 'Student, Islamabad',
    avatar: 'https://picsum.photos/seed/fatima/40/40',
    fallback: 'FZ',
    text: "The eco-challenges are fun and motivating! It feels great to be part of a community that's making a positive impact.",
  },
  {
    name: 'Usman T.',
    role: 'Cyclist, Lahore',
    avatar: 'https://picsum.photos/seed/usman/40/40',
    fallback: 'UT',
    text: 'Knowing the air quality before my morning ride is essential. This app gives me the data I need to plan my routes.',
  },
  {
    name: 'Dr. Sameera A.',
    role: 'General Physician',
    avatar: 'https://picsum.photos/seed/sameera/40/40',
    fallback: 'SA',
    text: "I recommend Saaf Hawa to my patients, especially those with respiratory issues. It's a valuable tool for managing health in polluted cities.",
  },
  {
    name: 'Ali H.',
    role: 'Environmental Activist',
    avatar: 'https://picsum.photos/seed/ali/40/40',
    fallback: 'AH',
    text: 'The crowdsourced eco-map is a brilliant idea. It empowers citizens to take an active role in monitoring and improving their local environment.',
  },
];

const TestimonialCard = ({
  testimonial,
}: {
  testimonial: (typeof testimonials)[0];
}) => {
  return (
    <Card className="w-[350px] shrink-0">
      <CardContent className="p-6 flex flex-col h-full justify-between">
        <p className="mb-6 italic text-foreground/80">"{testimonial.text}"</p>
        <div className="flex items-center gap-4">
          <Avatar>
            <AvatarImage src={testimonial.avatar} alt={testimonial.name} />
            <AvatarFallback>{testimonial.fallback}</AvatarFallback>
          </Avatar>
          <div>
            <p className="font-semibold">{testimonial.name}</p>
            <p className="text-sm text-muted-foreground">{testimonial.role}</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-4rem)]">
      <main className="flex-1">
        {/* Hero Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-4xl text-center space-y-6">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
                Clean Air, Clearer Health
              </div>
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl font-headline">
                Breathe Intelligently
              </h1>
              <p className="text-lg text-muted-foreground md:text-xl">
                Saaf Hawa delivers real-time air quality monitoring and
                AI-driven health recommendations to help you navigate your
                environment safely.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  href="/signup"
                  className={cn(buttonVariants({ size: 'lg' }))}
                >
                  Get Started for Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
                <Link
                  href="/about"
                  className={cn(
                    buttonVariants({ variant: 'outline', size: 'lg' })
                  )}
                >
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-muted/50">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-3 lg:gap-16">
              {features.map((feature) => (
                <div
                  key={feature.title}
                  className="flex flex-col items-start text-left p-6 border border-transparent hover:border-border rounded-lg transition-all"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary mb-4">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-bold mb-2 font-headline">
                    {feature.title}
                  </h3>
                  <p className="text-muted-foreground">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="w-full py-20 md:py-24 lg:py-32">
          <div className="container px-0">
            <div className="text-center max-w-3xl mx-auto mb-16 px-4 md:px-6">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">
                Loved by our Community
              </h2>
              <p className="mt-4 text-lg text-muted-foreground">
                See how Saaf Hawa is making a difference in people's lives
                across Pakistan.
              </p>
            </div>
            <div className="relative">
              <Marquee pauseOnHover className="[--duration:60s]">
                {testimonials.map((testimonial) => (
                  <TestimonialCard
                    key={testimonial.name}
                    testimonial={testimonial}
                  />
                ))}
              </Marquee>
              <div className="pointer-events-none absolute inset-y-0 left-0 w-1/3 bg-gradient-to-r from-background"></div>
              <div className="pointer-events-none absolute inset-y-0 right-0 w-1/3 bg-gradient-to-l from-background"></div>
            </div>
          </div>
        </section>

        {/* Our Mission Section */}
        <section className="w-full py-20 md:py-32 lg:py-40">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-4 max-w-3xl mx-auto">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-headline">
                From Data to Daily Decisions
              </h2>
              <p className="text-muted-foreground md:text-xl/relaxed">
                We transform complex air quality metrics into simple,
                actionable insights. Whether you're planning your commute or
                protecting your family, Saaf Hawa provides the clarity you
                need to act confidently.
              </p>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="w-full py-20 md:py-24 lg:py-32 bg-primary/10">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight font-headline">
                Take Control of Your Environment
              </h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                Join our community and start making healthier choices today.
                It’s free to sign up.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <Button asChild size="lg">
                <Link href="/signup">Join Now</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
